Resolving compile time errors and warnings
User::set_email. Qualified name is not allowed in member declaration.
fatal error C1075: '{': no matching token found (missing right parenthesis)
error C2672: 'std::regex_match': no matching overloaded function found
warning C26495: Variable 'Address::latitude' is uninitialized. Always initialize a member variable (type.6).